services:
  db:
    image: postgres:16-alpine
    container_name: finance-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mikhlasr7A
      POSTGRES_DB: finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finance-api:
    build: .
    container_name: finance-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - db

  caddy:
    image: caddy:2
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - finance-api

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
